### ISSUE TITLE
up to date recipes for GDAL and dependent libraries are not available on github

### ISSUE THREAD

**Issue by gillins** [conda/conda-recipes#567]
Makes it impossible to submit pull requests for improvements to these libraries. @groutr  has these recipes locally I understand.

Would be good to have libgdal, gdal and all other dependencies (hdf5 etc) on github.

**Comment by RutgerK** [comment]
Big +1 from me. Especially with packages like GDAL, which is very flexible about the supported formats, having a transparent build process is very useful. 

I was searching for a GDAL package in Conda which supports JPEG2000. And currently the only way to know, is to install it and run `gdalinfo --formats`. So i tried almost every build there is, 14 times installing it in different environments, with no luck though. Having some insight in the build process would eliminate the need to do so.

**Comment by gillins** [comment]
I have a recipe that builds JPEG2000 support for GDAL (with the openjpeg library). Once the recipes are available on github I will submit a pull request with the changes necessary. 
Building GDAL isn't totally straightforward on Windows. Hopefully an improved Conda package will reduce the need for users to do this.

**Comment by danclewley** [comment]
+1 from me. 
I would be happy to help out with improving the GDAL builds for OS X and Linux if the recipes were up to date. Myself, @gillins and @petebunting have been building our own packages for GDAL almost since the launch of binstar and hosting on http://anaconda.org/osgeo/gdal (note we are not affiliated with the Open Source Geospatial Foundation - just big users OSGEO software). Going from the downloads and messages we receive a lot of people are using our builds of GDAL packages due to various problems with the official builds. However, creating new packages is very much driven by our needs. For example, we rarely make builds for Python 2.7 as we aren't using it.
It would be great if we could continue to contribute our combined knowledge of building GDAL and dependencies on various platforms here so good GDAL builds become part of the official repositories. I'm sure this would be of great benefit to the the geospatial Python community.

**Comment by Woodstonelee** [comment]
the gdal build on the default anaconda channel does not support jpeg2000 that is a format adopted by the ESA's Sentinel-2 mission. We are going to use more and more this driver. It would be great if we can rebuild the gdal on the default channel with this support.

**Comment by gillins** [comment]
This is a good point - over time popular formats will change and the community will want to request changes to the Conda GDAL build. All the cool analysis tools in Conda aren't that useful if we can't read the data in the first place....

Is it part of Continuum's plan to allow community contributions to the GDAL build?

**Comment by msarahan** [comment]
Absolutely. We are moving to work with conda-forge to better enable the community to improve the packages that are available.  I will add gdal to our priority list of packages to transition. This should happen on the 1-2 week timescale.

**Comment by groutr** [comment]
I'm still learning the basics of conda-forge, but I plan to submit PRs for the gdal stack to conda-forge over the coming days.  I will link the PRs to this issue.

**Comment by gillins** [comment]
Now available under conda-forge
