### ISSUE TITLE
libgfortran / libgcc conflict

### ISSUE THREAD

**Issue by jschueller** [conda/conda-recipes#666]
hi,

I cannot seem to find the libgfortran recipe.

I'm interested because it would seem that the binary package libgfortran provided in the official repo
conflicts with the libgcc package wich also brings fortran libs, but compiled with a more recent gcc:
```
ImportError: /home/blork/miniconda2/lib/python2.7/site-packages/openturns/../../.././libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/blork/miniconda2/lib/python2.7/site-packages/openturns/../../../libblas.so.3)
```

As a result of this conflict the lapack package I provide for OpenTURNS and linked against the package libgcc is unusable after installation of libgfortran, as of dependency of scipy.

Would it be possible to access the libgfortran recipe or to have some more info how the binary version available in official repos is produced ?

The idea behind linking to libgcc was to ensure all my packages do not rely on my host system libs for reproducible builds and so as to be working on older distros (apparently it's built on centos 5 ?), so some our users with debian 6 are happy.

Bonus question : it seems conda does not handle file conflicts between packages, eg libgfortran.so, is it by design ?

j

**Comment by msarahan** [comment]
ping @ilanschnell

**Comment by Zaharid** [comment]
This is also reported here:

https://github.com/ContinuumIO/anaconda-issues/issues/686

As seen from the reference links, it does impact on quite a few projects relying on conda builds.

**Comment by msarahan** [comment]
So what is the optimal situation here, just so I understand?  libgfortran and libgcc need to provide the same version, but does it matter which version (old or new)?  It's easy to update everything to a current version, but does that work for you?

Long-term, libgcc should phase out including libgfortran and other libraries besides libgcc.  Packages should instead depend only on the runtimes that they actually use.  There is probably some transition period where libgcc has run dependencies on other packages - because people have been using libgcc where a more specific package would have been better.

**Comment by Zaharid** [comment]
I believe that if properly configure, newer is surely better, because it can be backwards compatible. In fact, the old version of libgfortran included in conda gives a lot of problems to built my code.

A bad situation that happens now is that custom packages built with libgcc that were working fine break when users install scipy.

**Comment by msarahan** [comment]
For now, a fix is to force-install libgcc after installing scipy/libgfortran.  Not a good fix, but hopefully helps get people running.

I'll try to address this.  We have a concern that bumping the build number may not fix people getting the correct package, as constraints like >=3 <4 don't actually take build number into account.  We'll see how much of a problem that is once we get this updated package out.

cc @groutr

**Comment by jschueller** [comment]
I think the current version of gcc libs (4.8) is fine to run on many systems, as long as it's compiled on your old centos5 build machine to not so-depend on a newer libc6 that would break backward-compatibility.

Otherwise I'm looking forward for version-matching and non-conflicting libgcc/libgfortran packages !

**Comment by jschueller** [comment]
@msarahan it seems libgfortran 3.0.0-1 from anaconda can now be installed over libgcc without the symbol problem, (libgcc still providing fortran libs):
https://anaconda.org/anaconda/libgfortran/files
https://anaconda.org/anaconda/libgcc/files

Unfortunately the scipy package still expclicitely depends on the old libgfortran package version, maybe it needs a rebuild:
```
The following NEW packages will be INSTALLED:

    scipy:       0.17.0-np111py27_2

The following packages will be DOWNGRADED:

    libgfortran: 3.0.0-1 --> 3.0-0  
```

**Comment by msarahan** [comment]
Thanks @jschueller I will try to rebuild scipy today.

**Comment by jschueller** [comment]
@msarahan, did you succeed bumping scipy ?

**Comment by msarahan** [comment]
I have built them, but they fail many tests unless you also update libgcc to the version corresponding to the GCC 5.2 docker image.  I am including that as a new dependency, and will upload them later this afternoon.

**Comment by Zaharid** [comment]
If you are including libgcc as a dependency, isn't libgfortran redundant?

**Comment by msarahan** [comment]
yes, except that we are trying to split its many libraries out into their own packages.  Eventually, libgcc should only include actually libgcc, and libgfortran will need to be here.  The redundancy is harmless from my point of view, but if you have reason to remove it, I'll certainly take it into consideration.

**Comment by Zaharid** [comment]
Well, the reason would be that having to packages that overlap files is what caused this issue in the first place. In my opinion one should make sure that all the overlapping files are the same (as in same checksum), otherwise the environment is not really deterministic. But if that is solved for good and will remain that way, so be it.

**Comment by msarahan** [comment]
No, it's definitely not solved for good.  I hope we're headed in the right direction, though.  In the interim, libgcc will become a partial metapackage: it will depend on libgfortran at runtime, so that it still provides the library for people who did their dependencies wrong, but it will not actually package the library, so that it won't overlap.

**Comment by msarahan** [comment]
The rebuilds of scipy are up for linux-x64.  x86 is something that I haven't fully worked out with our docker image.  We use multilib compilation with gcc for 32-bit support, but some programs read system information in other ways, and try to build 64-bit code instead.

I'm closing this issue for now.  Reopen or comment as necessary.

**Comment by jschueller** [comment]
works!
thanks a lot @msarahan
